// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Express = require("bs-express/src/Express.bs.js");
var MiddlewareAsCompleteJs = require("./middlewareAsComplete.js");

function queryJson(req) {
  return Express.$$Request.query(req);
}

function middlewareAsComplete(prim, prim$1, prim$2) {
  return MiddlewareAsCompleteJs(prim, prim$1, prim$2);
}

exports.queryJson = queryJson;
exports.middlewareAsComplete = middlewareAsComplete;
/* Express Not a pure module */
