// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Express = require("bs-express/src/Express.bs.js");
var Server_Middleware = require("./Server_Middleware.bs.js");

function Make(Cfg) {
  var use = function (router) {
    var fn;
    switch (Cfg.verb) {
      case /* GET */0 :
          fn = Express.Router.get;
          break;
      case /* POST */1 :
          fn = Express.Router.post;
          break;
      case /* PUT */2 :
          fn = Express.Router.put;
          break;
      case /* DELETE */3 :
          fn = Express.Router.$$delete;
          break;
      
    }
    return Curry._3(fn, router, Cfg.path, Server_Middleware.andThenHandle(Cfg.middleware, Cfg.handler));
  };
  return {
          use: use
        };
}

exports.Make = Make;
/* Express Not a pure module */
