// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Prom = require("bs-prom/src/Prom.bs.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Server = require("./Server.bs.js");
var Server_Log = require("./Server_Log.bs.js");
var Server_Handler = require("./Server_Handler.bs.js");
var Server_Middleware = require("./Server_Middleware.bs.js");

var app = Curry._1(Server.App.make, undefined);

Curry._2(Server.App.use, app, Server_Log.middleware(undefined, undefined));

function handler(_req, res, param) {
  Server_Log.warn("Inside a handler");
  return Prom.wrap(Curry._2(Server.$$Response.sendString, "Heeellllllloooooooooooooo", Curry._2(Server.$$Response.status, /* Ok */0, res)));
}

var Health = Server_Handler.Make({
      path: "/",
      verb: /* GET */0,
      middleware: Server_Middleware.none,
      handler: handler
    });

var router = Curry._4(Server.Router.make, undefined, undefined, undefined, undefined);

Curry._1(Health.use, router);

Curry._2(Server.App.useRouter, app, router);

Curry._5(Server.App.listen, app, 3000, undefined, (function (param) {
        return Server_Log.info("server started");
      }), undefined);

exports.app = app;
exports.Health = Health;
exports.router = router;
/* app Not a pure module */
